backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # Allow drafts
media_folder: "src/_assets/img/uploads" # Media files will be stored in the repo under src/_assets/img/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /img/uploads
#display_url: https://example.com
editor:
  preview: true

collections:
  - name: "pages" # Used in routes, e.g., /cms/collections/pages
    label: "Pages" # Used in the UI
    label_singular: "Page" # singular label for certain elements in the editor
    description: "Individual site pages"
    folder: "pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: "frontmatter"
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "Short Title", name: "short_title", widget: "string", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "SEO Description", name: "seo_description", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {label: "Cover Image Alt Text", name: "cover_image_alt", widget: "string", required: false}
      - {label: "Content", name: "body", widget: "markdown", required: false}
      - {label: "Navigation Title", name: "nav_title", widget: "string", required: false}
      - {label: "Navigation", name: "navigation", widget: "number", required: false}

collections:
  - name: "articles" # Used in routes, e.g., /cms/collections/articles
    label: "Articles" # Used in the UI
    label_singular: "Article" # singular label for certain elements in the editor
    description: "This is the Articles archive excerpt."
    folder: "articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: "frontmatter"
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "Short Title", name: "short_title", widget: "string", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "SEO Description", name: "seo_description", widget: "string", required: false}
      - {label: "Topics", name: "topics", widget: "list", default: [ "General" ]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {label: "Cover Image Alt Text", name: "cover_image_alt", widget: "string", required: false}
      - {label: "Content", name: "body", widget: "markdown", required: false}